### ISSUE TITLE
post-installation script subprocess returned error exit status 6

### ISSUE THREAD

**Issue by butteryak** [google/aiyprojects-raspbian#761]
getting an error why trying to install aiy-voicebonnet-soundcard-dkms

sudo apt-get install -y aiy-voicebonnet-soundcard-dkms

any help would be appreciate, I know possibly there have been some changes on the aiy side that may no longer be compatable...also changes to rasbperry OS.  looking like a kernal incompatability

Error! Bad return status for module build on kernel: 5.15.61+ (armv6l)
Consult /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/make.log for more information.
dpkg: error processing package aiy-voicebonnet-soundcard-dkms (--configure):
 installed aiy-voicebonnet-soundcard-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 aiy-voicebonnet-soundcard-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by butteryak** [comment]
DKMS make.log for aiy-voicebonnet-soundcard-3.0 for kernel 5.15.61+ (armv6l)
Mon 17 Oct 16:47:58 BST 2022
make: Entering directory '/usr/src/linux-headers-5.15.61+'
  CC [M]  /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.o
In file included from /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.c:25:
/var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/rt5645.h:12:10: fatal error: sound/rt5645.h: No such file or directory
   12 | #include <sound/rt5645.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.o] Error 1
make: *** [Makefile:1898: /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.15.61+'

**Comment by denics** [comment]
Here you can find up to date drivers: https://github.com/google/aiyprojects-raspbian/issues/697

**Comment by builderjer** [comment]
> DKMS make.log for aiy-voicebonnet-soundcard-3.0 for kernel 5.15.61+ (armv6l) Mon 17 Oct 16:47:58 BST 2022 make: Entering directory '/usr/src/linux-headers-5.15.61+' CC [M] /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.o In file included from /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.c:25: /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/rt5645.h:12:10: fatal error: sound/rt5645.h: No such file or directory 12 | #include <sound/rt5645.h> | ^~~~~~~~~~~~~~~~ compilation terminated. make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.o] Error 1 make: *** [Makefile:1898: /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build] Error 2 make: Leaving directory '/usr/src/linux-headers-5.15.61+'



> DKMS make.log for aiy-voicebonnet-soundcard-3.0 for kernel 5.15.61+ (armv6l) Mon 17 Oct 16:47:58 BST 2022 make: Entering directory '/usr/src/linux-headers-5.15.61+' CC [M] /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.o In file included from /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.c:25: /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/rt5645.h:12:10: fatal error: sound/rt5645.h: No such file or directory 12 | #include <sound/rt5645.h> | ^~~~~~~~~~~~~~~~ compilation terminated. make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.o] Error 1 make: *** [Makefile:1898: /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build] Error 2 make: Leaving directory '/usr/src/linux-headers-5.15.61+'



> DKMS make.log for aiy-voicebonnet-soundcard-3.0 for kernel 5.15.61+ (armv6l) Mon 17 Oct 16:47:58 BST 2022 make: Entering directory '/usr/src/linux-headers-5.15.61+' CC [M] /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.o In file included from /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.c:25: /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/rt5645.h:12:10: fatal error: sound/rt5645.h: No such file or directory 12 | #include <sound/rt5645.h> | ^~~~~~~~~~~~~~~~ compilation terminated. make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build/snd-aiy-voicebonnet.o] Error 1 make: *** [Makefile:1898: /var/lib/dkms/aiy-voicebonnet-soundcard/3.0/build] Error 2 make: Leaving directory '/usr/src/linux-headers-5.15.61+'

I am having the same issue, did @denics solution work for you?
